// ── DATA ──────────────────────────────────────────────────────────────────────
export const PROJECTS = [
  { num:"01", year:"2024", type:"Generative AI · CV", name:"Caption Engine",
    sub:"AI-Powered Social Media Caption Generation",
    desc:"Built an AI-powered caption generator achieving 0.75+ CLIP relevance on 100+ images by integrating BLIP for image description, LangChain-orchestrated Mistral-7B captioning, and CLIP for similarity ranking. Deployed on Streamlit with Distinct-2 (>0.95) and Self-BLEU (<0.05) for diversity optimization.",
    tech:["BLIP","Mistral-7B","LangChain","CLIP","Streamlit","Python","Computer Vision"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"02", year:"2024", type:"Multimodal AI", name:"BertNet",
    sub:"Sales Prediction via Images & Descriptions",
    desc:"Engineered a multimodal sales prediction system using EfficientNetB5 for image feature extraction and BERT for text embeddings, achieving 75% accuracy. Optimized feature fusions (text: 83%, image: 71%) using transfer learning and fine-tuning with hybrid model handling missing data and class imbalance.",
    tech:["EfficientNetB5","BERT","Transfer Learning","Multimodal AI","PyTorch","Scikit-learn"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"03", year:"2024", type:"ML · Predictive", name:"MetroPT3",
    sub:"Failure Prediction System",
    desc:"Attained 100% accuracy in failure prediction using bidirectional feature elimination and LASSO-based feature selection. Enhanced prediction efficiency by 20% and cut maintenance downtime by 45% leveraging Extreme Learning Machine, XGBoost, and Neural Networks in a robust ensemble model.",
    tech:["XGBoost","Neural Networks","LASSO","Ensemble Methods","Feature Selection","Python"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"04", year:"2023", type:"Computer Vision", name:"Intruder Detection",
    sub:"Real-Time YOLOv5 Security System",
    desc:"Achieved 98% intruder detection accuracy by training YOLOv5 on a custom dataset and deploying with OpenCV for real-time classification of unknown persons via webcam feed. Enhanced security with 6 image processing techniques and results surfaced on a Flask UI.",
    tech:["YOLOv5","OpenCV","Python","Flask","Computer Vision"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"05", year:"2023", type:"Analytics · BI", name:"Car Market Analysis",
    sub:"US Used Car Market — Tableau Dashboard",
    desc:"Engineered an interactive Tableau dashboard analyzing 2,500 US car listings, increasing data interpretability by 40% through 10+ custom visualizations. Framework features dynamic filters, 95% confidence forecasting models, and state geographic insights.",
    tech:["Tableau","Data Visualization","Forecasting","Statistical Analysis"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"06", year:"2023", type:"Recommender · R", name:"CineMatch",
    sub:"Smart Movie Recommendations with R",
    desc:"Built a recommendation system in R on the MovieLens dataset (20M+ ratings), implementing user-based collaborative filtering with Pearson correlation and custom similarity scoring. Features real-time recommendations and a Shiny interface for personalized suggestions.",
    tech:["R","MovieLens","Collaborative Filtering","Pearson Correlation","Shiny"],
    href:"https://github.com/RekhaDeenadayal" },
  { num:"07", year:"2023", type:"BI · Education", name:"EdTech Analytics",
    sub:"Course Analytics using Power BI",
    desc:"Designed an interactive Power BI dashboard analyzing 3K courses across 10+ categories, uncovering trends in course distribution, language preferences, subtitle impact, and instructor ratings. Refined engagement insights from 8,000+ interactions to enhance learner experience.",
    tech:["Power BI","Data Analytics","Business Intelligence"],
    href:"https://github.com/RekhaDeenadayal" },
];

export const EXPERIENCE = [
  { role:"Software Engineer", company:"Accenture",
    location:"Chennai, India", period:"Mar 2022 – Aug 2024", years:"2022–2024",
    points:[
      "Owned end-to-end development of enterprise React dashboards integrated with SAP backend APIs, supporting 10,000+ daily active users across a global client deployment — reducing manual reporting effort by 60%.",
      "Architected a reusable component library of 40+ UI modules that cut average feature delivery time by 35% across 3 concurrent project tracks, becoming the team's shared design-system standard.",
      "Optimised critical data-fetch pipelines with caching and lazy-loading strategies, cutting average page load time from 4.2s to under 1.1s — directly improving client satisfaction scores on quarterly reviews.",
      "Drove the migration of a legacy jQuery codebase to a modern React + TypeScript stack across 80K+ lines of production code, zero regressions in post-release monitoring over a 6-month rollout.",
      "Mentored 2 junior engineers through onboarding and code reviews; established team-wide PR conventions and automated lint/test gates that reduced review cycle time by 40%.",
    ],
    tech:["React","TypeScript","JavaScript","SAP APIs","REST APIs","Node.js","CI/CD","Jest"],
  },
  { role:"Software Engineering Intern", company:"Kaar Technologies",
    location:"Chennai, India", period:"Mar 2021 – Feb 2022", years:"2021–2022",
    points:[
      "Delivered 12 production features across 6 sprint cycles with a 100% on-time rate, consistently ranked top contributor in retrospective velocity reviews.",
      "Rebuilt the client onboarding form flow with advanced validation and conditional logic, reducing form-submission errors by 72% and cutting support tickets related to data entry by half.",
      "Integrated third-party REST APIs for real-time logistics tracking, enabling live shipment status updates that replaced a daily-batch manual process — saving ~3 hours of ops work per day.",
    ],
    tech:["React","Node.js","Express","MySQL","REST APIs","Agile/Scrum"],
  },
];

export const SKILLS = {
  "AI & ML":              ["Machine Learning","Deep Learning","NLP (Hugging Face, NLTK, spaCy)","Transformers","TensorFlow","PyTorch","Computer Vision (OpenCV)","Reinforcement Learning","Statistical Analysis","A/B Testing"],
  "Generative AI & LLMs": ["LangChain","Retrieval-Augmented Generation (RAG)","LangGraph","AI Agents","GANs","Diffusion Models","LLMs (OpenAI, Llama)","Prompt Engineering","PEFT (LoRA/QLoRA)","vLLM","AutoGen","CrewAI","Whisper","LlamaIndex","Pinecone","AWS Bedrock"],
  "Programming":          ["Python","TypeScript","R","MATLAB","C","Data Structures & Algorithms"],
  "Data Engineering":     ["SQL","PySpark","Hadoop","ETL","Big Data","Airflow","Power BI","Tableau","Data Mining","Microsoft Excel"],
  "Cloud & Deployment":   ["AWS","Vertex AI","MLOps","MLflow","Docker","Git","CI/CD","Kubernetes","Terraform","Streamlit","FastAPI","RESTful APIs"],
};

export const COFFEE_IMGS = [
  "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80",
  "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80",
  "https://images.unsplash.com/photo-1485808191679-5f86510bd0a0?auto=format&fit=crop&w=600&q=80",
  "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80",
];
